"Allow all items to be added" = false
"Morph in the offhand instead of mainhand" = false
"Whitelisted Items" = ["botania:twig_wand", "appliedenergistics2:network_tool", "immersiveengineering:tool", "buildersguides:mallet", "environmentaltech:tool_multiblock_assembler", "bloodmagic:ritual_reader", "draconicevolution:crystal_binder", "crossroads:omnimeter"]
"Whitelisted Names" = ["wrench", "screwdriver", "hammer", "rotator", "configurator", "crowbar"]
"Blacklisted Mods" = ["tconstruct", "intangible"]
"Mod Aliases" = ["mythicbotany=botania", "rsrequestify=refinedstorage", "extrastorage=refinedstorage", "thermalexpansion=thermalfoundation", "thermaldynamics=thermalfoundation", "thermalcultivation=thermalfoundation", "mekanismgenerators=mekanism", "xnet=rftoolsbase", "rftoolspower=rftoolsbase", "rftoolsutility=rftoolsbase", "rftoolsstorage=rftoolsbase", "rftoolscontrol=rftoolsbase", "rftoolsbuilder=rftoolsbase", "rftoolsdimensions=rftoolsbase"]

